name: arxlib
description: "A lightweight Dart client for the arXiv API."
version: 0.0.2
repository: https://github.com/JinZr/arxlib.git

environment:
  sdk: ^3.10.8

dependencies:
  http: ^1.6.0
  xml: ^6.6.1

dev_dependencies:
  test: ^1.29.0
  lints: ^6.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
